### ISSUE TITLE
installing dependencies failed

### ISSUE THREAD

**Issue by evayfang2019** [yjx1217/NanoTrans#7] opened 2024-08-09 04:47 UTC
http://hannonlab.cshl.edu/fastx_toolkit/fastx_toolkit_0.0.13_binaries_Linux_2.6_amd64.tar.bz2
ERROR 502: Bad Gateway.

**the url is unavailable**

I don't know if fastx_toolkit_0.0.14 works [bioconda](https://anaconda.org/bioconda/fastx_toolkit/files) & [github](https://github.com/agordon/fastx_toolkit/releases).
If not, could you please fix the bug? Such as preset the fastx_toolkit_0.0.13 in Nanotrans.

**Comment by yjx1217** [comment] 2024-08-09 12:50
Dear @evayfang2019 ,

Thanks for trying NanoTrans and let us know the issue.
The issue was caused by a recent URL change of this software. 
We have applied a fix for this issue >
https://github.com/yjx1217/NanoTrans/commit/ed6fe4effc7935e34d642ef333c62392cf866d4a

Thanks for reporting this!

Best,
Jia-Xing

**Closed as completed** 2024-08-10 17:10 UTC
